# This is a basic workflow to help you get started with Actions

name: HACKORD_BUILD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.10.4 

#       - name: PyInstaller Windows
#         # You may pin to the exact commit or the version.
#         # uses: JackMcKew/pyinstaller-action-windows@a8dee21ad01bbc7e7363d445bb632691b95ba057
#         uses: JackMcKew/pyinstaller-action-windows@v0.1.2
#         with:
#           # Directory containing source code (optional requirements.txt).
#           path: ${{ github.workspace }}

      - uses: robinraju/release-downloader@v1.6
        with: 
          repository: "upx/upx"
          latest: false
          tag: "v4.0.0"
          fileName: "upx-4.0.0-win64.zip"
          tarBall: false
          zipBall: false
          # Relative path under $GITHUB_WORKSPACE to place the downloaded file(s)
          # It will create the target directory automatically if not present
          # eg: out-file-path: "my-downloads" => It will create directory $GITHUB_WORKSPACE/my-downloads
          out-file-path: ""

      - name: Extract UPX
        run: 7z x ./upx-4.0.0-win64.zip
      
      - name: test
        run: |
          dir
          dir ./upx

#       - name: Install PyInstaller
#         run: pip install pyinstaller

#       - name: Package for windows.
#         run: pyinstaller --noconfirm --onefile --console --icon "NONE" --upx-dir "C:/Users/Wieszaczek/Desktop/upx-4.0.0-win64" --clean --log-level "ERROR" --add-data "C:/Users/Wieszaczek/Desktop/HackordV2/mod;mod/" --add-data "C:/Users/Wieszaczek/Desktop/HackordV2/haisolver;haisolver/"  "C:/Users/Wieszaczek/Desktop/HackordV2/HackordV2.py"
